front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index}
login:
    path: /login
    defaults: {_controller: BackBundle:Administrateur:login}
create:
    path: /create
    defaults: { _controller: BackBundle:Administrateur:create}
profil:
    path: /profil
    defaults: { _controller: BackBundle:Administrateur:profil}
logout:
    path: /logout
    defaults:  { _controller: BackBundle:Administrateur:logout}
AllAdmin:
    path: /admin/list
    defaults:  { _controller: BackBundle:Administrateur:allAdmin}
update:
    path: /update
    defaults:  { _controller: BackBundle:Administrateur:update}
desinscription:
    path: /signOff
    defaults:  { _controller: BackBundle:Administrateur:delete}