back_homepage:
    path:     /
    defaults: { _controller: BackBundle:Default:index }

back_machine:
    path:     /machine
    defaults: { _controller: BackBundle:Machine:index }

back_machine_create:
    path:     /machine/create
    defaults: { _controller: BackBundle:Machine:create }

back_machine_update:
    path:     /machine/update
    defaults: { _controller: BackBundle:Machine:update }


back_machine_delete:
    path:     /machine/delete
    defaults: { _controller: BackBundle:Machine:delete }


back_createincident:
    path:     /incident/create
    defaults: { _controller: BackBundle:Incidents:createincident }

back_indexallincidents:
    path:     /incident/affiche
    defaults: { _controller: BackBundle:Incidents:allincidents }

back_indexincident:
    path:     /incident/{id}
    defaults: { _controller: BackBundle:Incidents:incident }


back_incidentend:
    path:     /incident/end/{id}
    defaults: { _controller: BackBundle:Incidents:incidentend }

login:
    path: /admin/login
    defaults: {_controller: BackBundle:Administrateur:login}
create:
    path: /admin/create
    defaults: { _controller: BackBundle:Administrateur:create}
profil:
    path: /admin/profil
    defaults: { _controller: BackBundle:Administrateur:profil}
logout:
    path: /admin/logout
    defaults:  { _controller: BackBundle:Administrateur:logout}
AllAdmin:
    path: /admin/list
    defaults:  { _controller: BackBundle:Administrateur:allAdmin}

update:
    path: /admin/update
    defaults:  { _controller: BackBundle:Administrateur:update}

