back_homepage:
    path:     /back
    defaults: { _controller: BackBundle:Default:index }

back_createsalle:
    path:     /createSalle
    defaults: { _controller: BackBundle:Salle:createSalle }

back_updatesalle:
    path:     /updateSalle
    defaults: { _controller: BackBundle:Salle:updateSalle }

back_deletesalle:
    path:     /deleteSalle
    defaults: { _controller: BackBundle:Salle:deleteSalle }
