#Routes Machines

#Route Supprimer une  machine back fait
back_machine_delete:
    path:     /machine/delete/{id}
    defaults: { _controller: BackBundle:Machine:delete }

back_machine_ping:
    path:     /machine/ping/{id}
    defaults: { _controller: BackBundle:Machine:ping }

#Routes Salles

#Suppression d'une salle ( a refaire ) back
back_deletesalle:
    path:     /salle/delete/{id}
    defaults: { _controller: BackBundle:Salle:delete }

#Route Création des dates de fin d'incidents back
back_incidentend:
    path:     /incident/end/{id}
    defaults: { _controller: BackBundle:Incidents:incidentend }

#Routes Admin

#Route Login partie admin back
login:
    path: /admin/login
    defaults: {_controller: BackBundle:Administrateur:login}

#Route logout admin back
admin_logout:
    path: /admin/logout
    defaults:  { _controller: BackBundle:Administrateur:logout}

#Route Création d'un admin back
admin_create:
    path: /admin/create
    defaults: { _controller: BackBundle:Administrateur:create}

#Route Affiche profile  admin back
admin_profil:
    path: /admin/profil
    defaults: { _controller: BackBundle:Administrateur:profil}

#Route Affiche tout les  admins back
AllAdmin:
    path: /admin/list
    defaults:  { _controller: BackBundle:Administrateur:allAdmin}

#Route Mis à jour admin back
admin_update:
    path: /admin/update
    defaults:  { _controller: BackBundle:Administrateur:update}

#Route affichant le profil d'un utilisateur lambda
admin_profilOther:
    path: /admin/list/details
    defaults:  { _controller: BackBundle:Administrateur:AdminDetails}

#Route pour supprimer un admin
admin_delete:
    path: /admin/list/delete
    defaults:  { _controller: BackBundle:Administrateur:delete}