back_homepage:
     path:     /back
     defaults: { _controller: BackBundle:Default:index }

#Machine
back_machine:
     path:     /machine
     defaults: { _controller: BackBundle:Machine:index }

back_machine:
    path:     /machine
    defaults: { _controller: BackBundle:Machine:index }

back_machine_create:
    path:     /machine/create
    defaults: { _controller: BackBundle:Machine:create }

back_machine_update:
    path:     /machine/update
    defaults: { _controller: BackBundle:Machine:update }


back_machine_delete:
    path:     /machine/delete
    defaults: { _controller: BackBundle:Machine:delete }

#Incident
back_createincident:
    path:     /incident/create
    defaults: { _controller: BackBundle:Incidents:createincident }

back_indexallincidents:
    path:     /incident/affiche
    defaults: { _controller: BackBundle:Incidents:allincidents }

back_indexincident:
    path:     /incident/{id}
    defaults: { _controller: BackBundle:Incidents:incident }


back_incidentend:
    path:     /incident/end/{id}
    defaults: { _controller: BackBundle:Incidents:incidentend }

#User
login:
    path: /admin/login
    defaults: {_controller: BackBundle:Administrateur:login}
create:
    path: /admin/create
    defaults: { _controller: BackBundle:Administrateur:create}
profil:
    path: /admin/profil
    defaults: { _controller: BackBundle:Administrateur:profil}
logout:
    path: /admin/logout
    defaults:  { _controller: BackBundle:Administrateur:logout}
AllAdmin:
    path: /admin/list
    defaults:  { _controller: BackBundle:Administrateur:allAdmin}

update:
    path: /admin/update
    defaults:  { _controller: BackBundle:Administrateur:update}

#Salle
back_createsalle:
    path:     /salle/create
    defaults: { _controller: BackBundle:Salle:createSalle }

back_updatesalle:
    path:     /salle/update
    defaults: { _controller: BackBundle:Salle:updateSalle }

back_deletesalle:
    path:     /salle/delete
    defaults: { _controller: BackBundle:Salle:deleteSalle }

#Dashboard
back_board:
    path:     /board
    defaults: { _controller: BackBundle:Dashboard:dashboard }

back_dashboard:
    path:     /dashboard/board
    defaults: { _controller: BackBundle:Dashboard:dashboard }
